name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Enter web folder
        run: cd web

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
